version: "3.9"
services:
  khanwagera_db:
    container_name: khanawagera_db
    image: postgres:latest
    restart: always
    networks:
      - postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=khanawagera_development_v1
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

networks:
  postgres:
    name: postgres
  